---
 title: Title
 output:
  html_document:
    css: styles.css
---

**[Fisher's Least Significant Difference: a Multiple Comparison
Procedure]{.underline}**

If the null hypothesis in an ANOVA is rejected, then you may conclude
that not all the population means are equal. However, ANOVA by itself
cannot tell you *which* of the means are different. It could be only one
group that has a different mean with the rest being equal, or two
groups, or all of the groups could have different means. ANOVA is silent
in that respect.

Consider the case where there are four groups in an ANOVA analysis, so
the null and alternative hypotheses are:

$H_{0}:\ \mu_{1} = \mu_{2} = \mu_{3} = \mu_{4}$

$H_{A}:Not\ all\ the\ population\ means\ are\ equal$

If the null is rejected, then the question becomes: which mean is not
equal to the others? Are they all different, or is only one or two
different from the others? This is where *multiple comparison
procedures* come in. Multiple comparison procedures are only used [after
ANOVA confirms a difference]{.underline}, to find out which groups have
a different mean from the others.

Multiple comparison procedures test pairs of means, and you have to run
one test per pair. Mathematically, we need to ask:
$\text{is\ }\mu_{1} \neq \mu_{2}?\ \text{is\ }\mu_{2} \neq \mu_{3}?\ \text{is\ }\mu_{3} \neq \mu_{4}?$
is
$\mu_{1} \neq \mu_{3}?\ \text{is\ }\mu_{2} \neq \mu_{4}?\text{is}\ \mu_{1} \neq \mu_{4}?\ \ $Notice
how those questions look like alternative hypotheses in a two tailed
test? Well, that is exactly what they are used for in multiple
comparisons.

Fisher's Least Significant Difference (Fisher's LSD) procedure is
commonly used for multiple comparisons. Fisher's LSD is a special type
of two-tailed t test.

There are three different methods to use Fisher's LSD: a traditional t
test; a modified t test; and, a confidence interval. All three methods
will come to the same conclusion, because they are all different ways of
using the same information. All three ways are presented in this handout
and in 13.3 in the book, but in this class only **METHOD 2** will be
used on the homework and on exams.

**[*Method 1*: *Fisher's LSD as a series of traditional t
tests*]{.underline}*:***

1)  Take any two groups from the ANOVA (here they are labeled $i$ and
    $j$ just to differentiate them). Set an $\alpha$ significance level.

2)  The hypotheses are:

> $H_{0}:\ \mu_{i} = \mu_{j}$
>
> $H_{A}:\ \mu_{i} \neq \mu_{j}$

3)  The test statistic is:

> $t_{\text{test}} = \frac{{\overline{x}}_{i}\  - \ {\overline{x}}_{j}}{\sqrt{\text{MSE}\left( \frac{1}{n_{i}}\  + \ \frac{1}{n_{j}} \right)}}$

$$\text{where\ }$$

> ${\overline{x}}_{i} = the\ sample\ mean\ of\ group\ i$

$${\overline{x}}_{j} = the\ sample\ mean\ of\ group\ j$$

$$MSE = Mean\ Square\ Error\ from\ the\ ANOVA$$

$$n_{j} = sample\ size\ of\ the\ j^{\text{th}}\text{\ group}$$

> and the degrees of freedom are $df_{2} = n_{T} - k$ from the ANOVA

4)  The rejection rules are:

    a.  $p\text{-}value\ approach:\ Reject\ H_{0}\text{\ if\ }2T\ p\text{-}value \leq \ \alpha$

    b.  $Critical\ Value\ approach:Reject\ H_{0}\text{\ if\ }t_{\text{test}} \leq - t_{\frac{\alpha}{2}}\text{\ or\ }t_{\text{test}} \geq t_{\frac{\alpha}{2}}\ $

$$with\ df = n_{T}\ –k$$

$$n_{T} = total\ sample\ size,\ from\ the\ ANOVA$$

$$k = the\ number\ of\ groups\ in\ the\ ANOVA$$

> NOTE: the df here are the same df from the $\text{MSE}$ in the ANOVA

5)  If the null hypothesis is rejected, then the two group means
    $\mu_{i}\text{\ and\ }\mu_{j}\ $are different. If the null
    hypothesis is not rejected, then there is no evidence that
    $\mu_{i}\text{\ and\ }\mu_{j}\ $are different.

6)  Conduct one test for each possible pair of means from the ANOVA

***[Method 2: Fisher's LSD as a series of modified t tests]{.underline}:
(This is the one we will use in this course)***

Take any two groups from the ANOVA (here they are labeled $i$ and $j$
just to differentiate them). Set an $\alpha$ significance level.

1)  The hypotheses are:

> $H_{0}:\ \mu_{i} = \mu_{j}$
>
> $H_{A}:\ \mu_{i} \neq \mu_{j}$

2)  The test statistic is:

> ${\overline{x}}_{i}\  - \ {\overline{x}}_{j}$
>
> $\text{where}$
>
> ${\overline{x}}_{i} = the\ sample\ mean\ of\ group\ i$
>
> ${\overline{x}}_{j} = the\ sample\ mean\ of\ group\ j$

3)  The Least Significant Difference is:

> $LSD = t_{\alpha/2}\sqrt{\text{MSE}\left( \frac{1}{n_{i}}\  + \ \frac{1}{n_{j}} \right)}\text{\ where\ the\ }2T\ t_{\alpha/2}\text{\ Critical\ Value\ has\ }df_{2} = n_{T} - k$

$$\text{and}$$

$${n_{i} = sample\ size\ of\ the\ i^{\text{th}}\text{\ group}
}{n_{j} = sample\ size\ of\ the\ j^{\text{th}}\text{\ group}
}{n_{T} = the\ total\ sample\ size\ from\ the\ ANOVA
}{k = the\ number\ of\ groups\ in\ the\ ANOVA}$$

and the rejection rule is:

> $\text{If\ }\left| {\overline{x}}_{i}\  - \ {\overline{x}}_{j} \right| \geq LSD\ then\ reject\ H_{0}\text{\ and\ accept\ }H_{A}\text{.\ }$
>
> $\text{If\ }\left| {\overline{x}}_{i}\  - \ {\overline{x}}_{j} \right| < LSD\ then\ \text{do\ not}\text{\ reject\ }H_{0}\text{\ and\ conclude\ }H_{A}\text{\ is\ unsupported.\ \ \ }$

4)  If the null hypothesis is rejected, then the two group means
    $\mu_{i}\text{\ and\ }\mu_{j}$ are different. If the null hypothesis
    is not rejected, then there is no evidence that
    $\mu_{i}\text{\ and\ }\mu_{j}$ are different.

5)  Conduct one test for each possible pair of means from the ANOVA.
    Note that this method is very efficient to use for multiple
    comparisons in balanced designs (i.e. those in which the groups are
    all the same size). In balanced designs, you only have to compute
    the LSD once because it will be the same no matter which two groups
    you are testing. Then you can compute the difference between each
    pair of means and compare the absolute value of each difference to
    the LSD to see whether to reject the null. In unbalanced designs
    (i.e. those in which the groups are not all the same size), you will
    have to compute the LSD individually for each test.

***[Method 3: Fisher's LSD as a series of confidence
intervals]{.underline}:***

Take any two groups from the ANOVA (here they are labeled $i$ and $j$
just to differentiate them). Set an α significance level.

1)  The hypotheses are:

> $H_{0}:\ \mu_{i} = \mu_{j}$
>
> $H_{A}:\ \mu_{i} \neq \mu_{j}$

2)  Calculate a $100\left( 1 - \alpha \right)\%$ confidence interval for
    the difference between $\mu_{i}\text{\ and\ }\mu_{j}$ using the
    following equation:

> ${\overline{x}}_{i}\  - \ {\overline{x}}_{j}\  \pm LSD\ where\ $
>
> $LSD = t_{\frac{\alpha}{2}}\sqrt{\text{MSE}\left( \frac{1}{n_{i}}\  + \ \frac{1}{n_{j}} \right)}\ \ and\ the\ t\ critical\ value\ has\ df = n_{T} - k$

3)  The rejection rule is:

> $\text{Reject\ }H_{0}\text{\ if\ the\ confidence\ interval\ does\ not\ include\ zero.}$

4)  If the null hypothesis is rejected, then the two group means
    $\mu_{i}\text{\ and\ }\mu_{j}$ are different.

5)  Conduct one test for each possible unique pair of means from the
    ANOVA

**[\
]{.underline}**

*Example.* We are going to use Fisher's LSD to test the groups from the
Grocery Store Ad example on Ch 13: Handout \#4.

*Part 1.* Using Method 2, perform a Fisher's LSD procedure to test
whether the population mean produce spending for the group that received
Ad A is different than Ad B. Use an $\alpha = 0.05$ significance level.
If you can confirm a difference between the means, which group spent
more on average?

*Example, part 2:* Using Method 2, perform a Fisher's LSD procedure to
test whether the population mean produce spending for the group that
received Ad A is different than Ad C. Use an $\alpha = 0.05$
significance level. If you can confirm a difference between the means,
which group spent more on average?

*Example, part 3:* Using Method 2, perform a Fisher's LSD procedure to
test whether the population mean produce spending for the group that
received Ad B is different than Ad C. Use an $\alpha = 0.05$
significance level. If you can confirm a difference between the means,
which group spent more on average?
