---
 title: Title
 output:
  html_document:
    css: styles.css
---

**[Experimental Design]{.underline}**

An *experimental design* is a plan and a process for gathering data in
which the researcher controls, modifies, or manipulates at least one
variable. The purpose of gathering data in any research design,
including experimental design, is to test hypotheses.

In a study with an experimental design, the researcher begins with an
idea about cause and effect. The researcher wants to test whether a
treatment causes a response. To do this, each treatment is applied to a
different group, and the mean responses of the groups are measured and
compared to each other.

[Terminology:]{.underline}

-   A [factor]{.underline} is an explanatory variable, also called an
    Independent Variable (IV). It is the variable that the researcher
    controls, modifies, or manipulates to see what happens.

    -   The [treatments]{.underline} are different levels or categories
        of the factor.

-   [Experimental units]{.underline} are the objects or subjects whose
    response the researcher is measuring. Experimental units are
    assigned to [treatment groups]{.underline} which are groups of
    experimental units receiving a particular treatment.

-   A [response variable]{.underline} is the Dependent Variable (DV). It
    is what the researcher expects to vary with different treatments.

    -   A [response]{.underline} is a single measurement of the response
        variable for a given experimental unit.

-   [Random assignment]{.underline} is the process of randomly assigning
    experimental units to treatment groups, or randomly assigning
    treatments to experimental units. **Random assignment makes the
    groups equivalent at the outset of the study.... so any changes you
    see in the groups after applying the treatments, can be attributed
    to the treatments themselves.**

Two types of experimental design:

1)  [Fully randomized experimental design]{.underline}: The treatments
    are randomly assigned to the groups, or, equivalently, the groups
    are randomly assigned to the treatments. In either case, the
    treatments are randomly assigned [by the researcher]{.underline}.
    This is the key component of a fully randomized experimental design.
    The researcher imposes changes or otherwise manipulates the
    treatments that the groups receive.

    a.  **[Can]{.underline} prove cause and effect.** This is because
        the process of randomly assigning treatment groups makes the
        groups equivalent at the outset. Everything other than the
        treatment that could affect the response is randomly distributed
        among the groups. Therefore, any difference in the mean response
        between treatment groups must be due to the treatment itself.

        i.  In a fully randomized experimental design, it is appropriate
            to call the Independent Variable (the factor) the *cause*
            and the Dependent Variable (the response) the *effect.* This
            is because you can prove cause and effect with a fully
            randomized experiment.

2)  [Nonrandomized experimental design]{.underline}: also called
    quasi-experimental design. The treatments are not randomly assigned
    by the researcher, but different groups still receive different
    treatments.

    a.  **[Cannot]{.underline} prove cause and effect.**

Both experimental designs contrast with another type of study design:
[observational design]{.underline}. In observational designs, outcomes
are observed and measured for different groups, but there is no
assignment of treatments to different groups. Researchers using
observational designs look at ongoing behavior -- they [do not impose
any changes]{.underline} in any variables. These studies are useful to
illuminate associations and relationships between variables but **they
cannot prove cause and effect**. In order for observational studies to
have validity, they must use random sampling from the population of
interest.

In both nonrandomized experimental design and observational design,
there is no way to completely rule out the possibility that there are
pre-existing differences between treatment groups that explain differing
responses. This is why these types of studies do not prove cause and
effect.

**[Experimental Design: Exercise]{.underline}**

A local grocery store would like to increase sales on produce. This
grocery store tracks purchases at the customer level.

The grocery store decided that an effective way to boost sales of
produce might be to redesign the weekly ad that customers receive. In
the current design (Weekly Ad A), produce is on an inside page, the
pictures are small, and the emphasis is on price. In the second design
(Weekly Ad B), the produce is featured on the front page, beautifully
photographed in full color, and there are recipes that incorporate
produce. In the third design (Weekly Ad C) is the same as Design B
except that there are no recipes.

The grocery store takes a random sample of customers. These customers
are randomly assigned to receive one of the three Weekly Ad designs. The
customers' purchases are tracked and their weekly spending on produce is
measured.

1\) What is the **factor** in this experiment?

2\) What are two other terms for **factor**?

3\) What are the **treatments**? How many treatments are there?

4\) How many groups of customers will there be in this experiment?

5\) What is the **response variable** in this experiment?

6\) What is another term for **response variable**?

7\) What are the **experimental units**?

8\) Give an example of a **response** in this study.

9\) Is this a fully randomized experiment? How do you know?

10\) Suppose that differences in Weekly Spending on Produce are observed
among the groups after they receive the Ads. Can the researcher conclude
that the Weekly Ad Design *caused* those differences?
