---
 title: Title
 output:
  html_document:
    css: styles.css
---

[Introduction to Analysis of Variance (ANOVA)]{.underline}

ANOVA is a hypothesis testing procedure that allows us to test the
equality of three or more population means in one hypothesis test.

ANOVA is used to test whether the mean response differs between
treatment groups in fully randomized and quasi-experimental designs. It
is also used to test between-group differences in observational studies
when the samples are random.

1.  **[Formulating the Hypotheses:]{.underline}**

> There is only one general form of hypotheses for ANOVA. It is adapted
> to each particular ANOVA depending on how many groups there are in a
> particular analysis.
>
> NOTE: $k = the\ number\ of\ groups$

+----------------------------------------------------------------------+
| **Hypotheses for Analysis of Variance (ANOVA)**                      |
+======================================================================+
| $H_{0}:\mu_{1} = \ \mu_{2} = \ldots = \ \mu_{k}$                     |
|                                                                      |
| $$H_{A}:Not\ all\ of\ the\ means\ are\ equal$$                       |
+----------------------------------------------------------------------+
| **Answers questions about:**                                         |
+----------------------------------------------------------------------+
| Whether at least one group has a different mean than the others.     |
+----------------------------------------------------------------------+
| NOTE:                                                                |
|                                                                      |
| 1.  $\mu_{1}                                                         |
| ,\mu_{2},\ldots,\mu_{k}\text{\ are\ the\ means\ of\ the\ dependent\  |
| }\left( \text{response} \right)\text{\ variable\ for\ each\ group.}$ |
|                                                                      |
| 2.  $k = the\ number\ of\ groups$                                    |
|                                                                      |
| 3.  the alternative hypothesis may be stated as                      |
|     $H_{A}:At\ least\ two\ of\ the\ population$                      |
|                                                                      |
| > $\text{means\ are\ not\ equal}$. These two forms of $H_{A}$ are    |
| > equivalent to one another.                                         |
+----------------------------------------------------------------------+

2.  **[The Test Statistic:]{.underline}**

> In order to understand the test statistic, we need to know something
> about the process behind ANOVA. ANOVA estimates the variance of the
> dependent variable two different ways, and compares those variance
> estimates using an F test statistic. The two variance estimates are:

1)  The between-treatments estimate of the variance, also called the
    **Mean Square due to Treatments (MSTR)**

    a.  The MSTR is the variance estimated under the assumption that
        $H_{0}\ $is true

2)  The within-treatments estimate of the variance, also called the
    **Mean Square due to Error (MSE)**

    a.  The MSE is the variance estimated under the assumption that
        $H_{0}\ $is false

> The test statistic in ANOVA procedures is $F$, and it is the ratio of
> the two variance estimates: the MSTR and the MSE. The by-hand
> calculation of this test statistic is the subject of its own handout.
> The equation is:

$$F_{\text{test}} = \frac{\text{MSTR}}{\text{MSE}}$$

> with

$${numerator\ degrees\ of\ freedom = df_{1} = k - 1
}{denominator\ degrees\ of\ freedom = df_{2} = n_{T} - k}$$

> where

$${k = the\ number\ of\ groups
}{n_{T} = total\ sample\ size\ (of\ all\ the\ groups)}$$

3.  **[Deciding whether or not to Reject]{.underline}**
    $\mathbf{H}_{\mathbf{0}}$**:**

> ANOVA $F$ tests are always [**one-tailed, upper tail
> tests**.]{.underline} The reason for this is due to the nature of the
> two variance estimates: the MSTR and the MSE. Here is how ANOVA works.
> If $H_{0}$ is actually true and all the means of the groups are equal,
> then both the MSTR and the MSE will yield similar estimates of the
> true variance. Therefore, the ratio of MSTR and MSE (which is
> $F)\ $will be a small number -- too small to cause us to reject
> $H_{0}.$ If, on the other hand, $H_{0}$ is actually false, and the
> means of the groups are not all equal, the MSTR will vastly
> overestimate the true variance, while the MSE will estimate the true
> variance accurately. Therefore, the ratio of the MSTR and MSE (which
> is $F)\ $will be a large number -- large enough to cause us to reject
> $H_{0}.$ We only want to reject the null when the difference between
> MSTR and MSE is large, hence the use of the upper tail test.

+----------------------------------+----------------------------------+
| **When to Reject**               |                                  |
| $\mathbf{H}_{\mathbf{0}}$ **in   |                                  |
| ANOVA (the Test Statistic is**   |                                  |
| $\mathbf                         |                                  |
| {F}_{\mathbf{\text{test}}}$**)** |                                  |
+==================================+==================================+
|                                  | **Always an Upper Tail Test:**   |
+----------------------------------+----------------------------------+
| **p-value approach:**            | Calculate the upper tail         |
|                                  | $p\text{-}\text{value}$ of       |
|                                  | $F_{\text{test}}.$               |
|                                  |                                  |
|                                  | If the                           |
|                                  | $\text{UT\                       |
|                                  |  p}\text{-}value \leq \ \alpha,$ |
|                                  | then reject $H_{0}$ and accept   |
|                                  | $H_{A}.$                         |
|                                  |                                  |
|                                  | If the                           |
|                                  | $\tex                            |
|                                  | t{UT\ p}\text{-}value > \alpha$, |
|                                  | then do not reject               |
|                                  | $H_{0}\text{.\ }H_{A}$ is        |
|                                  | unsupported.                     |
+----------------------------------+----------------------------------+
| **Critical Value Approach:**     | If                               |
|                                  | $F_{\tex                         |
|                                  | t{test}} \geq F_{\alpha},\ $then |
|                                  | reject $H_{0}$ and accept        |
|                                  | $H_{A}.$                         |
|                                  |                                  |
|                                  | If                               |
|                                  | $F_{\text{test}} < F_{\alpha}$,  |
|                                  | then do not reject               |
|                                  | $H_{0}\text{.\ }H_{A}$ is        |
|                                  | unsupported.                     |
+----------------------------------+----------------------------------+
| NOTES:                           |                                  |
|                                  |                                  |
| 1)  $F_{\text{test}}\ $is the    |                                  |
|     Test Statistic               |                                  |
|                                  |                                  |
| 2)  $F_{\alpha}$ is the upper    |                                  |
|     tail Critical Value (from    |                                  |
|     the $F$ table).              |                                  |
|                                  |                                  |
| 3)  The                          |                                  |
|     $\text{numerator\            |                                  |
|  degrees\ of\ freedom} = k - 1$, |                                  |
|     $\text{denominator\ de       |                                  |
| grees\ of\ freedom} = n_{T} - k$ |                                  |
|                                  |                                  |
| where                            |                                  |
|                                  |                                  |
| $${k = the\ number\ of\ groups   |                                  |
| }{n_{T} = total\ sample\         |                                  |
|  size\ (of\ all\ the\ groups)}$$ |                                  |
+----------------------------------+----------------------------------+

4.  **[Interpreting the test]{.underline}:**

+----------------------------------+----------------------------------+
| **How to Interpret an ANOVA:**   |                                  |
+==================================+==================================+
| **When you:**                    | **Interpretation:**              |
+----------------------------------+----------------------------------+
| **Reject**                       | At the $\text{α\ }$significance  |
| $\mathbf{H}_{\mathbf{0}}$        | level, we can conclude that not  |
|                                  | all of the population means are  |
|                                  | equal. *Could also be stated:*   |
|                                  | At the $\text{α\ }$significance  |
|                                  | level, we can conclude that at   |
|                                  | least one of the populations has |
|                                  | a different mean than the        |
|                                  | others.                          |
+----------------------------------+----------------------------------+
| **Do not reject**                | At the $\text{α\ }$significance  |
| $\mathbf{H}_{\mathbf{0}}$        | level, we cannot conclude that   |
|                                  | any of the population means are  |
|                                  | different from one another.      |
+----------------------------------+----------------------------------+
| NOTES:                           |                                  |
|                                  |                                  |
| 1)  When $H_{0}\ $is rejected,   |                                  |
|     you can then perform         |                                  |
|     comparisons of pairs of      |                                  |
|     means from the ANOVA to      |                                  |
|     determine which one is       |                                  |
|     different (or which ones are |                                  |
|     different)                   |                                  |
+----------------------------------+----------------------------------+

**[Assumptions Underlying ANOVA Tests]{.underline}**

ANOVA relies on [three assumptions]{.underline}:

1)  For each population, the response variable (dependent variable) is
    normally distributed.

    a.  Each treatment group in an experiment represents a potentially
        different population, and in each population, the response
        variable, also called the dependent variable, must be normally
        distributed. This holds true for groups in observational studies
        as well.

2)  The variance of the response variable is the same for all of the
    populations.

3)  The observations must be independent.

    a.  In experimental designs, this assumption is satisfied by the use
        of [random assignment]{.underline} to place experimental units
        into treatment groups.

    b.  In observational designs, this assumption is satisfied by using
        [random sampling]{.underline}.
