---
 title: Title
 output:
  html_document:
    css: styles.css
---

[ANOVA: In-Class Exercises]{.underline}

*Exercise 1.* Let's suppose that the grocery store from Chapter 13:
Handout \#1 decided to perform the experiment. The objective of the
experiment is to see whether any one of the three different ad designs
causes people to buy more produce. The store randomly samples customers
from its database, and then randomly assigns 22 of those customers to
receive Weekly Ad A, 21 of the customers to receive Weekly Ad B, and 20
of the customers to receive Weekly Ad C. Weekly produce purchases by
each customer are tracked, and the sample mean and variance of weekly
produce spending for each group are calculated. For each group, the
weekly spending on produce is normally distributed, and the population
variances are assumed to be equal.

+---+-------------+-----------+------------------------+-----------------+
| j | Treatment   | $$n_{j}$$ | Sample Mean            | Sample Variance |
|   |             |           |                        |                 |
|   |             |           | $${\overline{x}}_{j}$$ | $${s_{j}}^{2}$$ |
+===+=============+===========+========================+=================+
| 1 | Weekly Ad A |           | 25.11                  | 9.21            |
+---+-------------+-----------+------------------------+-----------------+
| 2 | Weekly Ad B |           | 28.51                  | 10.05           |
+---+-------------+-----------+------------------------+-----------------+
| 3 | Weekly Ad C |           | 29.20                  | 9.91            |
+---+-------------+-----------+------------------------+-----------------+

Use ANOVA to test whether the means for the three treatment groups are
equal at an $\alpha\  = \ 0.05$ significance level. Use your results to
fill in the ANOVA table.

**ANOVA Table for Exercise 1: Grocery Store Ads**

  **Source of Variation**   **Sum of Squares**   **Degrees of Freedom**   **Mean Square**   **F**   **Critical value of F**
  ------------------------- -------------------- ------------------------ ----------------- ------- -------------------------
  **Treatments**                                                                                    
  **Error**                                                                                         
  **Total**                                                                                         

*\
*

*Exercise 2.* In a study with a fully randomized experimental design,
four treatments were applied to randomly assigned groups of experimental
units. The first treatment group had 12 experimental units, the second
treatment group had 9 experimental units, the third treatment group had
9 experimental units, and the fourth treatment group had 14 experimental
units.

Given the following ANOVA table, test whether the population means are
equal at the α = 0.01 significance level.

  **Source of Variation**   **Sum of Squares**   **Degrees of Freedom**   **Mean Square**   **F**   **Critical value of F**
  ------------------------- -------------------- ------------------------ ----------------- ------- -------------------------
  **Treatments**                                                                                    
  **Error**                 50                                                                      
  **Total**                 65                                                                      
