---
 title: Title
 output:
  html_document:
    css: styles.css
---

**[Hypothesis Testing in Simple Linear Regression]{.underline}**

The **Regression Model**,
$\mathbf{y =}\mathbf{\beta}_{\mathbf{0}}\mathbf{+}\mathbf{\beta}_{\mathbf{1}}\mathbf{x + \epsilon}$,
gives the relationship between $\text{x\ }$and $y$ in the
[population]{.underline}. From the sample, regression calculates the
**Estimated Regression Equation**,
$\widehat{\mathbf{y}}\mathbf{=}\mathbf{b}_{\mathbf{0}}\mathbf{+}\mathbf{b}_{\mathbf{1}}\mathbf{x}$,
which gives the relationship between $\text{x\ }$and $y$ in the
[sample]{.underline}.

**VERY IMPORTANT:**
$\mathbf{\ }\mathbf{b}_{\mathbf{1}}\mathbf{\text{\ is\ NOT\ the\ same\ as\ }}\mathbf{\beta}_{\mathbf{1}}\mathbf{\text{\ and\ }}\mathbf{b}_{\mathbf{0}}\mathbf{\text{\ is\ NOT\ the\ same\ as\ }}\mathbf{\beta}_{\mathbf{0}}\mathbf{!!!!!!}$

You must use hypothesis tests to learn about the $\beta^{'}s$ from the
$b's$

The following table summarizes the possible relationships between
$\text{x\ }$and $y:$

  **Slope Coefficient**          **Relationship between** $\mathbf{\text{x\ }}$**and** $\mathbf{y}$
  ------------------------------ --------------------------------------------------------------------
  $$\text{If\ }\beta_{1} > 0$$   Positive linear relationship in the population
  $$\text{If\ }\beta_{1} < 0$$   Negative linear relationship in the population
  $$\text{If\ }\beta_{1} = 0$$   No relationship in the population

In order to conclude that there [is]{.underline} a relationship between
$\text{x\ }$and $y\ $in the population, we need to confirm that
$\beta_{1} \neq 0$. But we cannot observe the population parameter
$\beta_{1}$ -- we only have the sample statistic $b_{1}.$ How can we
draw conclusions about a population parameter from a sample?? We have to
use good old hypothesis testing!

If the hypothesis test confirms a relationship between x and y, we
typically say that *"the relationship between x and y is statistically
significant,"* or, *"there is a statistically significant relationship
between x and y."*

**[Hypothesis Test for Significance of the Population
Slope]{.underline}** $\mathbf{\beta}_{\mathbf{1}}$

1)  **[Formulating the Hypotheses]{.underline}:**

> There is only one form of hypotheses, because in regression the
> question is: is the population slope different from zero? If the slope
> of a line is zero, there is no relationship between x and y. If the
> slope is either positive or negative, then there is a relationship
> between x and y. Therefore, the question calls for a two-tailed test.

+----------------------------------------------------------------------+
| **Hypotheses about the Slope Coefficient**                           |
| $\mathbf{\beta}_{\mathbf{1}}$ **in Regression**                      |
+======================================================================+
| **Two-Tailed Test**                                                  |
+----------------------------------------------------------------------+
| $$H_{0}:\ \beta_{1} = 0$$                                            |
|                                                                      |
| $$H_{A}:\ \beta_{1} \neq 0$$                                         |
+----------------------------------------------------------------------+
| Answers the question:                                                |
+----------------------------------------------------------------------+
| Whether the population slope is different from zero.                 |
|                                                                      |
| That is to say, whether there is a relationship between              |
| $\text{x\ and\ y}$                                                   |
+----------------------------------------------------------------------+

**[\
]{.underline}**

2)  **[The Test Statistic]{.underline}:**

> The sampling distribution of $b_{1}$ is the $t$ distribution, and so
> we use a $t$ test statistic. The test statistic is:

$$t_{\text{test}} = \frac{b_{1}}{s_{b_{1}}}$$

$${b_{1} = the\ sample\ slope\ coefficient,\ from\ the\ regression\ output
}{s_{b_{1}} = the\ standard\ error\ on\ the\ slope\ coefficient,\ from\ the\ regression\ output}$$

> and the degrees of freedom are $df = n - p - 1$

$${\text{where\ n} = the\ number\ of\ observations
}{p = the\ number\ of\ independent\ variables\ \left( x^{'}s \right)\text{\ in\ the\ ERE}}$$

3)  **[Deciding whether or not to Reject]{.underline}**
    $\mathbf{H}_{\mathbf{0}}$**:**

+----------------------------------+----------------------------------+
|                                  | **For this Two-Tailed Test:**    |
+==================================+==================================+
| **p-value approach:**            | The two-tailed                   |
|                                  | $p\text{-}\text{value}$ is two   |
|                                  | times the one-tailed probability |
|                                  | of $t_{\text{test}}.$            |
|                                  |                                  |
|                                  | If the                           |
|                                  | $2T                              |
|                                  | \ p\text{-}value \leq \ \alpha,$ |
|                                  | then reject $H_{0}$ and accept   |
|                                  | $H_{A}.$                         |
|                                  |                                  |
|                                  | If the                           |
|                                  | $2T\ p\text{-}value > \ \alpha,$ |
|                                  | then do not reject $H_{0}$.      |
|                                  | $H_{A}$ is unsupported.          |
|                                  |                                  |
|                                  | **NOTE: the                      |
|                                  | [two-tailed]{.underline}**       |
|                                  | $\mathbf{                        |
|                                  | p}\text{-}\mathbf{\text{value}}$ |
|                                  | **is reported by Excel in the    |
|                                  | Regression Output!!**            |
+----------------------------------+----------------------------------+
| **Critical Value Approach:**     | If                               |
|                                  | $t_{\text{test}} \               |
|                                  | leq {- t}_{\alpha/2}\text{\ OR}$ |
|                                  | $t_{                             |
|                                  | \text{test}} \geq t_{\alpha/2}$, |
|                                  | then reject $H_{0}$and accept    |
|                                  | $H_{A}$.                         |
|                                  |                                  |
|                                  | If                               |
|                                  | ${- t}_{\alpha/2} <              |
|                                  | t_{\text{test}} < t_{\alpha/2}$, |
|                                  | then do not reject $H_{0}$.      |
|                                  | $H_{A}$ is unsupported.          |
+----------------------------------+----------------------------------+
| NOTES:                           |                                  |
|                                  |                                  |
| 1)  $t_{\text{test}}\ $is a Test |                                  |
|     Statistic                    |                                  |
|                                  |                                  |
| 2)  $\pm t_{\alpha/2}$ are       |                                  |
|     Critical Values              |                                  |
|                                  |                                  |
| 3)  The degrees of freedom are   |                                  |
|     $df = n - p - 1$             |                                  |
+----------------------------------+----------------------------------+

4)  **[Interpreting the test]{.underline}:**

> In the following interpretations, you should substitute in the actual
> meaning of $\text{x\ and\ y}$.

+----------------------------------+----------------------------------+
| **When you:**                    | **The Interpretation is:**       |
+==================================+==================================+
| **Reject**                       | At the $\alpha$ significance     |
| $\mathbf{H}_{\mathbf{0}}$        | level, we can conclude that the  |
|                                  | population slope is different    |
|                                  | from zero. Therefore, the        |
|                                  | relationship between             |
|                                  | $\text{x\ and\ y}$ is            |
|                                  | statistically significant.       |
|                                  |                                  |
|                                  | Further:                         |
|                                  |                                  |
|                                  | If $b_{1} > 0,\ $there is a      |
|                                  | positive linear relationship     |
|                                  | between $\text{x\ and\ y.}$      |
|                                  |                                  |
|                                  | If $b_{1} < 0,\ $there is a      |
|                                  | negative linear relationship     |
|                                  | between $\text{x\ and\ y.}$      |
+----------------------------------+----------------------------------+
| **Do not reject**                | At the $\alpha$ significance     |
| $\mathbf{H}_{\mathbf{0}}$        | level, we cannot conclude that   |
|                                  | the population slope is          |
|                                  | different from zero. Therefore,  |
|                                  | the relationship between         |
|                                  | $\text{x\ and\ y}$ is            |
|                                  | [not]{.underline} statistically  |
|                                  | significant.                     |
+----------------------------------+----------------------------------+
