---
 title: Title
 output:
  html_document:
    css: styles.css
---

[The t Distribution]{.underline}

The t distribution is a probability distribution that is frequently used
as a sampling distribution in hypothesis testing. In some ways, it is
similar to the z distribution, but it has several key differences as
well.

The t distribution:

-   has a total area under the curve of one

-   is approximately bell-shaped, but is not normal

-   has a mean of **zero**

-   is centered on the mean

-   is symmetrical around the mean

    -   "as above, so below the mean"

    -   upper tail t values are positive, lower tail t values are
        negative

-   is a family of distributions, so you must decide which t
    distribution to use

    -   The correct distribution to use in each case will be determined
        by the **degrees of freedom (df)**, which is calculated from
        information about the sample.

We will use the t distribution to decide whether to reject the null
hypothesis for t test statistics. For the Critical Value approach, we
can look up the CVs on the *t table*. For the p-value approach, we will
use Excel to calculate the p-values for t test statistics (see separate
handout).

[Using the *t table*:]{.underline}

The *t table* is a table of Critical Values of t at particular tail
probabilities.

-   Each row of the t table corresponds to a t distribution with the
    given degrees of freedom (df).

-   Each column of the t table refers to a different upper tail
    probability

-   We can use the t table for lower tail Critical Values too. Because
    the t distribution is symmetrical around the mean of zero, a lower
    tail Critical Value will be the negative of the upper tail Critical
    Value with the same tail probability.

*Example 1.* Use the t table to look up the following:

a)  The upper tail Critical Value of t at $\alpha = 0.05$ with degrees
    of freedom $df = 44$

b)  The lower tail Critical Value of t at $\alpha = 0.10$ with degrees
    of freedom $df = 82$

c)  The two-tailed Critical Values of t at $\alpha = 0.05$ with degrees
    of freedom $df = 37$*\
    *

*Example 2.* Consider a lower tail test at the $\alpha = 0.10$
significance level with a test statistic of $t_{\text{test}} = - 1.157$
and degrees of freedom $df = 38$.

a)  Use the Critical Value approach to decide whether to reject $H_{0}.$

b)  Use the p-value approach to decide whether to reject $H_{0}.$

*Example 3.* Consider a two-tailed test at the $\alpha = 0.01$
significance level with a test statistic of $t_{\text{test}} = 3.561$
and degrees of freedom $df = 85.$

a)  Use the Critical Value approach to decide whether to reject $H_{0}.$

b)  Use the p-value approach to decide whether to reject $H_{0}.$
