---
 title: Title
 output:
  html_document:
    css: styles.css
---

[Hypothesis Test about a Single Population Proportion]{.underline}

A company that puts on triathlons finds that over the years, 30% of its
race entrants were women. The company decides to add a women's only
triathlon as one of its races. The company knows this is a risky move.
It could attract more women to sign up for triathlons with the company
because they see it as welcoming to women. Or, female triathletes might
see the offering as patronizing and choose to race with some other
company. Finally, it could be that the same number of women would sign
up with or without a women's only race.

Sometime after introducing the women's only triathlon into its lineup of
races, the company took a random sample of 151 entries and found that 57
of the entries were for women.

Conduct and interpret a hypothesis test to find out if the population
proportion of women signing up for triathlons with this company has
changed at the $\alpha = 0.10$ significance level.
